# Generated by Django 5.0.6 on 2024-06-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_apikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name_plural': '2. API'},
        ),
    ]
