# Generated by Django 5.0.6 on 2024-06-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_apikey_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='expired_at',
            new_name='api_expired_at',
        ),
        migrations.RenameField(
            model_name='apikey',
            old_name='name',
            new_name='api_name',
        ),
        migrations.RenameField(
            model_name='apikey',
            old_name='token',
            new_name='api_token',
        ),
    ]
