# Generated by Django 5.0.6 on 2024-06-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_expired_at_apikey_api_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'verbose_name_plural': 'API'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'Biodata'},
        ),
        migrations.RenameField(
            model_name='apikey',
            old_name='api_expired_at',
            new_name='expired_at',
        ),
        migrations.RenameField(
            model_name='apikey',
            old_name='api_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='apikey',
            old_name='api_token',
            new_name='token',
        ),
    ]
