# Generated by Django 5.0.6 on 2024-06-23 01:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_apikey_options_alter_userinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='api_limit',
            field=models.IntegerField(default=5000),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='api_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='last_api_reset',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
